spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://148.66.135.118:3306/pay?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: root
      password: XNtMha9po[wO
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4
    password: 123456


# 自定义属性配置
renren:
  open-redis-logger: false
  auth-open: true
  data-sign-key: "Hello World!"
  sms-account: N6081253
  sms-password: SdJmGUYWEq1291
  sms-url: https://sms.253.com/msg/send
  sms-template: 【xxx】验证码${verifyCode}，用于您注册成为用户，5分钟内有效，请勿泄露他人，如非本人操作请忽略。
  sms-send-open: false # 是否开启短信下发
  sms-code-default: #"123456"
  sign-open: false
  smschinese-api: http://utf8.api.smschinese.cn/?Uid=zhangyang&Key=d41d8cd98f00b204e980&smsMob=${smsMob}&smsText=${smsText}
  task-open: false # 是否开启定时任务